首先，我们导入```torch```。请注意，虽然它被称为Pytorch，但我们应该带入```torch```而不是```pytorch```。





In [1]:
import torch

张量表示一个数值组成的数组，这个数组可能有多个维度。

In [2]:
x = torch.arange(12)
x

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

我们可以通过张量的```shape```属性来访问张量的形状和张量中元素的总数。

In [3]:
x.shape

torch.Size([12])

In [4]:
x.numel() #number of elements

12

要改变一个张量的形状而不改变元素的数量和元素值，我们可以调用```reshape```函数

In [6]:
x = x.reshape(3,4)  # 3 行 4 列
x

tensor([[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11]])

使用全0，全1、其他常量或者从特定分布中随机采样的数字。

In [7]:
torch.zeros((2,3,4))

tensor([[[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]],

        [[0., 0., 0., 0.],
         [0., 0., 0., 0.],
         [0., 0., 0., 0.]]])

In [8]:
torch.ones((2,3,4))

tensor([[[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]],

        [[1., 1., 1., 1.],
         [1., 1., 1., 1.],
         [1., 1., 1., 1.]]])

通过提供包含数值的Python列表（或嵌套列表）来为所需张量中的每个元素赋予确定值

In [9]:
torch.tensor([[2, 1, 4, 3],[1, 2, 3, 4],[4, 3, 2, 1]])

tensor([[2, 1, 4, 3],
        [1, 2, 3, 4],
        [4, 3, 2, 1]])

常见的标准算术运算符（```+```、```-```、```*```、```/```、```**```）都可以被升级为按元素运算。

In [10]:
x = torch.tensor([1.0, 2, 4, 8])
y = torch.tensor([2, 2, 2, 2])
x + y, x - y, x * y, x / y, x ** y

(tensor([ 3.,  4.,  6., 10.]),
 tensor([-1.,  0.,  2.,  6.]),
 tensor([ 2.,  4.,  8., 16.]),
 tensor([0.5000, 1.0000, 2.0000, 4.0000]),
 tensor([ 1.,  4., 16., 64.]))

我们也可以把多个张量连结在一起。

In [11]:
X = torch.arange(12, dtype = torch.float32).reshape((3,4))
Y = torch.tensor([[2.0, 1, 4, 3], [1, 2, 3, 4], [4, 3, 2, 1]])
torch.cat((X, Y), dim = 0), torch.cat((X, Y), dim = 1) # dim = 0 按行合并， dim = 1 按列合并

(tensor([[ 0.,  1.,  2.,  3.],
         [ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.],
         [ 2.,  1.,  4.,  3.],
         [ 1.,  2.,  3.,  4.],
         [ 4.,  3.,  2.,  1.]]),
 tensor([[ 0.,  1.,  2.,  3.,  2.,  1.,  4.,  3.],
         [ 4.,  5.,  6.,  7.,  1.,  2.,  3.,  4.],
         [ 8.,  9., 10., 11.,  4.,  3.,  2.,  1.]]))

通过逻辑运算符构建二元张量

In [12]:
X == Y

tensor([[False,  True, False,  True],
        [False, False, False, False],
        [False, False, False, False]])

对张量中所有元素进行求和会产生一个只有一个元素的张量。

In [13]:
X = torch.arange(12, dtype = torch.float32).reshape((3,4))
X.sum()

tensor(66.)

即使形状不同，我们仍然可以通过调用广播机制（broadcastingbroadcasting mechanism）来执行按元素操作。

In [14]:
a = torch.arange(3).reshape((3, 1))
b = torch.arange(2).reshape((1, 2))
a, b

(tensor([[0],
         [1],
         [2]]), tensor([[0, 1]]))

In [15]:
a + b # a.shape: (3,1) -> (3,2), b.shape: (1,2) -> (3,2)

tensor([[0, 1],
        [1, 2],
        [2, 3]])

可以用```[-1]```来选择最后一个元素，可以用```[1:3]```选择第二个和第三个元素。

In [16]:
X[-1], X[1:3]

(tensor([ 8.,  9., 10., 11.]), tensor([[ 4.,  5.,  6.,  7.],
         [ 8.,  9., 10., 11.]]))

除读取外，我们还可以通过指定索引来将元素写入矩阵。

In [17]:
X[1, 2] = 9
X

tensor([[ 0.,  1.,  2.,  3.],
        [ 4.,  5.,  9.,  7.],
        [ 8.,  9., 10., 11.]])

为多个元素赋值相同的值，我们只需要索引所有的元素，然后为他们赋值。

In [18]:
X[0:2, :] = 12
X

tensor([[12., 12., 12., 12.],
        [12., 12., 12., 12.],
        [ 8.,  9., 10., 11.]])

运行一些操作可能会导致为新结果分配内存

In [19]:
before = id(Y)
Y = Y + X
id(Y) == before

False

执行原地操作

In [21]:
Z = torch.zeros_like(Y)
print('id(Z):', id(Z))
Z[:] = X + Y
print('id(Z):', id(Z))

id(Z): 140248051008432
id(Z): 140248051008432


如果在后续计算中没有重复使用```X```，我们也可以使用```X[:] = X + Y```或```X += Y```来减少操作的内存开销。

In [23]:
before = id(X)
X += Y
id(X) == before

True

转换为NumPy张量

In [24]:
A = X.numpy()
B = torch.tensor(A)
type(A), type(B)

(numpy.ndarray, torch.Tensor)

将大小为1的张量转换为Python标量

In [25]:
a = torch.tensor([3.5])
a, a.item(), float(a), int(a)

(tensor([3.5000]), 3.5, 3.5, 3)